spring.application.name=Investo

spring.security.oauth2.client.registration.google.client-id=2955693838-0073bb2sehiic0jm4hgq2cdlv8svmqob.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/investo
spring.datasource.username=root
spring.datasource.password=Sachin@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect